Add support for UI specified environment variables to application module
massdriver-cloud/terraform-modules pull request #47
Opened 2022-09-18 00:05 UTC by chrisghill

2022-09-18 00:07 UTC, chrisghill commented on massdriver-application/main.tf
> +    { for env in local.params_envs: env.name => env.value }
`merge` in HCL handles collisions by prioritizing the last specified value, so here we are prioritizing params from the UI over those in the app definition.

2022-09-18 00:08 UTC, chrisghill commented on massdriver-application/main.tf
> +  base_envs = merge(
merge in HCL handles collisions by prioritizing the last specified value, so here we are prioritizing params from the UI over those in the app definition.

2022-09-18 21:31 UTC, WillBeebe commented
It was my impression that we wanted to move away from having an array of envs. That if the user wanted an env, they would define a param per env. Then in the app block, specify any envs from the params.

2022-09-18 22:02 UTC, chrisghill commented
I don't think we should burden users with having to learn JSON Schema and/or jq in order to do something as simple as setting an environment variable.

2022-09-19 17:22 UTC, mclacore approved these changes

2022-09-19 17:43 UTC, coryodaniel requested changes
Lets move any envs the user wants to expose on the params schema to a field that can be passed into the helm module `additionalEnv (list(object(name=string, value=string)) default: []`(?).

This will:
* allow us type the interface on the helm module
* not require a magic `envs` field in `massdriver-application` w/ magic subfields (name, value)
* push bundle devs towards using `app.envs` to document and validate their environment variables - we should add a note above params.envs

2022-09-20 02:32 UTC, chrisghill commented
Closing this in favor of https://github.com/massdriver-cloud/terraform-modules/pull/49

2022-09-20 02:32 UTC, closed without merging