app service uses subnet
massdriver-cloud/terraform-modules pull request #58
Opened 2022-10-15 23:26 UTC by WillBeebe

- enables logging for app service apps
- creates a subnet so that the app service can connect to things in the VNet

2022-10-15 23:27 UTC, WillBeebe commented on massdriver-application-azure-app-service/_variables.tf
> +variable "virtual_network_id" {
needed to create the subnet

2022-10-15 23:27 UTC, WillBeebe commented on massdriver-application-azure-app-service/_variables.tf
> +variable "command" {
adding container command. if blank, we use the default like k8s

2022-10-15 23:27 UTC, WillBeebe commented on massdriver-application-azure-app-service/auto-scaling.tf
> +resource "azurerm_monitor_autoscale_setting" "main" {
moved so grokking `main.tf` is easier

2022-10-17 15:58 UTC, mclacore requested changes

2022-10-17 15:58 UTC, mclacore commented on massdriver-application-azure-app-service/subnet.tf
> +}
Opened a [PR](https://github.com/massdriver-cloud/terraform-modules/pull/60) to add default network security group to this subnet.

2022-10-17 19:16 UTC, WillBeebe commented on massdriver-application-azure-app-service/subnet.tf
> +# Ideally, Massdriver picks an IP range that is not in use
Update to explain why we required a `/24`

2022-10-17 20:03 UTC, mclacore commented on massdriver-application-azure-app-service/subnet.tf
> +}
Disregard ^

2022-10-17 22:58 UTC, xpositivityx approved these changes

2022-10-17 23:01 UTC, merged